"""empty message

Revision ID: 2084f746818
Revises: 3f4f560c905
Create Date: 2014-10-23 12:37:53.102220

"""

# revision identifiers, used by Alembic.
revision = '2084f746818'
down_revision = '3f4f560c905'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
