"""empty message

Revision ID: 2f5f714543
Revises: 779612d349
Create Date: 2014-10-20 16:17:11.130557

"""

# revision identifiers, used by Alembic.
revision = '2f5f714543'
down_revision = '779612d349'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
