"""empty message

Revision ID: 30f9ade517
Revises: 491ba3bd514
Create Date: 2014-10-20 20:50:09.970228

"""

# revision identifiers, used by Alembic.
revision = '30f9ade517'
down_revision = '491ba3bd514'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
