"""empty message

Revision ID: 3f4f560c905
Revises: 30f9ade517
Create Date: 2014-10-23 12:28:31.380077

"""

# revision identifiers, used by Alembic.
revision = '3f4f560c905'
down_revision = '30f9ade517'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('crrnt_gm_forecast', sa.Float(), nullable=True))
    op.add_column('skus', sa.Column('optml_gm_forecast', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'skus', ['sku_num'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skus')
    op.drop_column('skus', 'optml_gm_forecast')
    op.drop_column('skus', 'crrnt_gm_forecast')
    ### end Alembic commands ###
