"""empty message

Revision ID: 47e6b2dd9f7
Revises: 2f5f714543
Create Date: 2014-10-20 16:18:03.548649

"""

# revision identifiers, used by Alembic.
revision = '47e6b2dd9f7'
down_revision = '2f5f714543'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
