"""empty message

Revision ID: 491ba3bd514
Revises: c05bf01cef
Create Date: 2014-10-20 20:46:37.904035

"""

# revision identifiers, used by Alembic.
revision = '491ba3bd514'
down_revision = 'c05bf01cef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
