"""empty message

Revision ID: 4ec4df1eb3a
Revises: 47e6b2dd9f7
Create Date: 2014-10-20 16:18:47.804873

"""

# revision identifiers, used by Alembic.
revision = '4ec4df1eb3a'
down_revision = '47e6b2dd9f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
