"""empty message

Revision ID: 58ca80d3632
Revises: 14a3fff4436
Create Date: 2014-11-06 06:47:08.591899

"""

# revision identifiers, used by Alembic.
revision = '58ca80d3632'
down_revision = '14a3fff4436'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('name', sa.String(length=64), nullable=False, default='clustername'))
    op.drop_column('categories', 'category')
    op.add_column('skus', sa.Column('cluster', sa.Integer(), nullable=True))
    op.alter_column('stores', 'lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
    op.alter_column('stores', 'lng',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'lng',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('stores', 'lat',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('skus', 'cluster')
    op.add_column('categories', sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('categories', 'name')
    op.drop_table('clusters')
    ### end Alembic commands ###
