"""empty message

Revision ID: c05bf01cef
Revises: 4ec4df1eb3a
Create Date: 2014-10-20 16:19:43.245062

"""

# revision identifiers, used by Alembic.
revision = 'c05bf01cef'
down_revision = '4ec4df1eb3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    ### end Alembic commands ###
